"""fire_alarm

Revision ID: 4a7e9c101440
Revises: 
Create Date: 2025-02-20 22:32:13.501454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a7e9c101440'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fire_alarms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fire_alarms_id'), 'fire_alarms', ['id'], unique=False)
    op.create_index(op.f('ix_fire_alarms_location'), 'fire_alarms', ['location'], unique=False)
    op.create_table('lights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lights_id'), 'lights', ['id'], unique=False)
    op.create_table('trashcans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trashcans_id'), 'trashcans', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('encodedImageData', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trashcans_id'), table_name='trashcans')
    op.drop_table('trashcans')
    op.drop_index(op.f('ix_lights_id'), table_name='lights')
    op.drop_table('lights')
    op.drop_index(op.f('ix_fire_alarms_location'), table_name='fire_alarms')
    op.drop_index(op.f('ix_fire_alarms_id'), table_name='fire_alarms')
    op.drop_table('fire_alarms')
    # ### end Alembic commands ###
